development:
  secret_key_base: AIzaSyCdkqynS4DcbA4IIQ5ckQtWleJtkReb7hk
  google_client_id: 58588679975-ska4i0tjgcq83d0soukkf13s9uas0ii9.apps.googleusercontent.com
  google_client_secret: 15VJogddHBVz8FE8PqmpbzrQ